# VPS configuration for RENSYS Engineering
  name: Crypto Wallet CI/CD
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      runs-on: self-hosted 
      strategy:
        matrix:
          node-version: [18.x]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - name: Route to Backend Directory
          run: cd ~/Crypto_wallet/backend/express
        - name: Git Pull
          run: cd ~/Crypto_wallet/ && git pull
        - name: Navigate to Express Directory
          run: cd ~/Crypto_wallet/backend/express
        - name: Install Dependencies
          run: cd ~/Crypto_wallet/backend/express && npm install
        - name: Build Application
          run: cd ~/Crypto_wallet/backend/express && npm run build && pm2 restart build/server.js



